# Generated by Django 3.1.2 on 2020-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=30)),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
